[[section-solution-strategy]]
== Solution Strategy

=== Technology decisions

==== Framework: React

Although it is not powerful as other options (like Angular), it is enough for developing this application and it is
less difficult to learn the basics, that is, the learning curve is faster. This idea is supported by its big community,
the introduction we have been given in class and the amount of projects of the course that have been developed with it
and that we can take as reference.

==== Language: TypeScript/JavaScript
It is the most spread option for developing web applications in React, so we expect to find enough resources to develop
our projects, in terms of information sources and libraries. Also, most of the members have worked with JavaScript in
SEW, so the transition to TypeScript should be smoother.

==== Database: MySQL
Relational databases are the most mature, market-accepted and robust databases, apart from their well-proven
performance. In addition, they are the ones we learned about the most in previous courses, and we expect to develop
smoothly the persistence of our application. It is more difficult to find a free database service for our application
which is not restrictive, but our application will not need a big persistence infrastructure.

[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape the system's architecture. These include

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the basis for many other detailed decisions or implementation rules.

.Form
Keep the explanation of these key decisions short.

Motivate what you have decided and why you decided that way,
based upon your problem statement, the quality goals and key constraints.
Refer to details in the following sections.
****
