[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

=== Public map generation
 
The placemarks of the public places are stored in a centralized database. The client is able to access this information through the API in order to generate the public map.

[plantuml,"public_map_generation",svg]
----
@startuml
<style>
root {
  Margin 40 5
}
</style>
skinparam Padding 10
skinparam ParticipantPadding 20
skinparam BoxPadding 100

skinparam ActorBackgroundColor #66bdf7
skinparam ActorBorderColor #66bdf7
skinparam ActorBorderThickness 2

skinparam ParticipantBackgroundColor #66bdf7
skinparam ParticipantBorderThickness 1.5

skinparam DatabaseBackgroundColor #66bdf7


actor User as u
participant Client as c

box "Server" #dedede
    participant API
    database Database as db
end box

u -> c: Access public map
c -> API: Request public places
API -> db: Query DB
API <-- db: Placemarks
c <-- API: Placemarks
c -> c: Generate map
u <-- c: Show map

@enduml
----


=== Add friends
 
The user will be able to add new friends with their POD's IDs. The application will try to request the friend's data and add a new friend to the user's POD. 

[plantuml,"add_friend_success",svg]
----
@startuml
<style>
root {
  Margin 40 5
}
</style>
skinparam Padding 10
skinparam ParticipantPadding 20
skinparam BoxPadding 100

skinparam ActorBackgroundColor #66bdf7
skinparam ActorBorderColor #66bdf7
skinparam ActorBorderThickness 2

skinparam ParticipantBackgroundColor #66bdf7
skinparam ParticipantBorderThickness 1.5

skinparam DatabaseBackgroundColor #66bdf7

Actor User as u
Participant Client as c
box Pod provider #dedede
  Database "Friend's POD" as fp
  Database "User's POD" as up
endbox

u->c: Provide friend's POD ID
c->fp: Request friend's data
c<--fp: Send data
c->up: Add friend
c->c: Update GUI
u<--c: Show confirmation message

@enduml
----

In case something goes wrong (invalid ID, connection error, etc.) the operation will be aborted and an error message will be displayed.

[plantuml,"add_friend_error",svg]
----
@startuml
<style>
root {
  Margin 40 5
}
</style>
skinparam Padding 10
skinparam ParticipantPadding 20

skinparam ActorBackgroundColor #66bdf7
skinparam ActorBorderColor #66bdf7
skinparam ActorBorderThickness 2

skinparam ParticipantBackgroundColor #66bdf7
skinparam ParticipantBorderThickness 1.5

skinparam DatabaseBackgroundColor #66bdf7

Actor User as u
Participant Client as c
Database "Friend's POD" as fp

u->c: Provide friend's POD ID
c->fp !!: Request friend's data
u<--c: Show error message

@enduml
----


=== Access to shared map

Users will be able able to have shared maps. The data of each place will be stored in the POD of its creator, while the placemarks, with references to the data locations, will be stored in the PODs of all users sharing the map.

[plantuml,"shared_map",svg]
----
@startuml
<style>
root {
  Margin 40 5
}
</style>
skinparam Padding 10
skinparam ParticipantPadding 20
skinparam BoxPadding 150

skinparam ActorBackgroundColor #66bdf7
skinparam ActorBorderColor #66bdf7
skinparam ActorBorderThickness 2

skinparam ParticipantBackgroundColor #66bdf7
skinparam ParticipantBorderThickness 1.5

skinparam DatabaseBackgroundColor #66bdf7

Actor User as u
Participant Client as c
box Pod provider #dedede
    Database "User's POD" as up 
    Database "Friend's POD" as fp
endbox

u->c: Select shared map
c->up: Request placemarks 
c<--up: Send data
c->c: Generate map
u<--c: Show map

u->c: Click on user's placemark
c->up: Request user's place information
c<--up: Send data
u<--c: Show place's information

u->c: Click on friend's placemark
c->fp: Request friend's place information
c<--fp: Send data
u<--c: Show place's information

@enduml
----


=== Post comments of a place

LoMap allows users to post comments about a place from the place's information window. This comments will be stored in the user's POD, being possible to make them private or delete them. The url of the comment is also stored in the 'comments' dataset of the place.

[plantuml,"post_comment",svg]
----

@startuml
<style>
root {
  Margin 40 5
}
</style>
skinparam Padding 10
skinparam ParticipantPadding 20
skinparam BoxPadding 100

skinparam ActorBackgroundColor #66bdf7
skinparam ActorBorderColor #66bdf7
skinparam ActorBorderThickness 2

skinparam ParticipantBackgroundColor #66bdf7
skinparam ParticipantBorderThickness 1.5

skinparam DatabaseBackgroundColor #66bdf7


actor User as u
participant Client as c

box "POD provider" #dedede
    database "Place's POD" as pod
    database "User's POD" as podUser
end box

u <-- c: Show map
u -> c: Click on placemark
u <-- c: Show popup
u -> c: Click on get info button
c -> pod: Request place
c <-- pod: Send data
u <-- c: Show place information
u -> c: Write comment
c -> podUser: Add comment
c -> pod: Add link to comment

@enduml

----


=== See comments of a place

The comments of a place can be seen from the 'reviews' tab of the place's information page. The application will request all the comments associated with a place and show them to the user.

[plantuml,"see_comments",svg]
----

@startuml
<style>
root {
  Margin 40 5
}
</style>
skinparam Padding 10
skinparam ParticipantPadding 20
skinparam BoxPadding 100

skinparam ActorBackgroundColor #66bdf7
skinparam ActorBorderColor #66bdf7
skinparam ActorBorderThickness 2

skinparam ParticipantBackgroundColor #66bdf7
skinparam ParticipantBorderThickness 1.5

skinparam DatabaseBackgroundColor #66bdf7


actor User as u
participant Client as c

box "POD provider" #dedede
    database "Place's POD" as pod
end box

u <-- c: Show map
u -> c: Click on placemark
u <-- c: Show popup
u -> c: Click on get info button
c -> pod: Request place
c <-- pod: Send data
u <-- c: Show place information
u -> c: Select comments tab
c -> pod: Request comments
c <-- pod: Send data
u <-- c: Show comments

@enduml

----
