[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

=== Public map generation
 
The placemarks of the public places are stored in a centralized database. The client is able to access this information through the API in order to generate the public map.

[plantuml,"public_map_generation",png]
----
@startuml
<style>
root {
  Margin 40 5
}
</style>
skinparam Padding 10
skinparam ParticipantPadding 20
skinparam BoxPadding 100

skinparam ActorBackgroundColor #66bdf7
skinparam ActorBorderColor #66bdf7
skinparam ActorBorderThickness 2

skinparam ParticipantBackgroundColor #66bdf7
skinparam ParticipantBorderThickness 1.5

skinparam DatabaseBackgroundColor #66bdf7


actor User as u
participant Client as c

box "Server" #dedede
    participant API
    database Database as db
end box

u -> c: Access public map
c -> API: Request public places
API -> db: Query DB
API <-- db: Placemarks
c <-- API: Placemarks
c -> c: Generate map
u <-- c: Show map

@enduml
----

=== Add friends
 
The user will be able to add new friends with their POD's IDs. The application will try to request the friend's data and add a new friend to the user's POD. 

[plantuml,"add_friend_success",png]
----
@startuml
<style>
root {
  Margin 40 5
}
</style>
skinparam Padding 10
skinparam ParticipantPadding 20

skinparam ActorBackgroundColor #66bdf7
skinparam ActorBorderColor #66bdf7
skinparam ActorBorderThickness 2

skinparam ParticipantBackgroundColor #66bdf7
skinparam ParticipantBorderThickness 1.5

skinparam DatabaseBackgroundColor #66bdf7

Actor User as u
Participant Client as c
Database "Friend's POD" as fp
Database "User's POD" as up

u->c: Provide friend's POD ID
c->fp: Request friend's data
c<--fp: Send data
c->up: Add friend
c->c: Update GUI
u<--c: Show confirmation message

@enduml
----

In case something goes wrong (invalid ID, connection error, etc.) the operation will be aborted and an error message will be displayed.

[plantuml,"add_friend_error",png]
----
@startuml
<style>
root {
  Margin 40 5
}
</style>
skinparam Padding 10
skinparam ParticipantPadding 20

skinparam ActorBackgroundColor #66bdf7
skinparam ActorBorderColor #66bdf7
skinparam ActorBorderThickness 2

skinparam ParticipantBackgroundColor #66bdf7
skinparam ParticipantBorderThickness 1.5

skinparam DatabaseBackgroundColor #66bdf7

Actor User as u
Participant Client as c
Database "Friend's POD" as fp

u->c: Provide friend's POD ID
c->fp !!: Request friend's data
u<--c: Show error message

@enduml
----
