[[section-design-decisions]]
== Design Decisions


[role="arc42help"]
****
.Contents
Important, expensive, large scale or risky architecture decisions including rationals.
With "decisions" we mean selecting one alternative based on given criteria.

Please use your judgement to decide whether an architectural decision should be documented
here in this central section or whether you better document it locally
(e.g. within the white box template of one building block).

Avoid redundancy. Refer to section 4, where you already captured the most important decisions of your architecture.

.Motivation
Stakeholders of your system should be able to comprehend and retrace your decisions.

.Form
Various options:

* List or table, ordered by importance and consequences or:
* more detailed in form of separate sections per decision
* ADR (architecture decision record) for every important decision
****

=== Centralized database

There will be a centralized database in charge of storing the information of public places. This information will be the minimum possible in order to be able to generate the map (i.e., the placemarks). Any other data related to this places will be accessed through a reference to the place creator's POD.

|===
| **Advantages** | **Disadvantages**
| Decentralization of data. | Certain data redundancy in the server and the POD.
| Less dependence on the server. | May lead to data inconsistency.
| The server requires fewer resources. |
| Better performance when generating the map. |
| Public and private places are treated in the same way. |
| Simpler architecture of the application. |
|===

We consider that the improvement in performance along with the data decentralization are worth the possible data redundancy and inconsistency, provided there won't be concurrent modifications of the same public place (it's creator is the only one who can modify the data) and the consequences of data inconsistency between the placemark and the place do not have a significant impact on the application. 

=== Client side computing over server side computing

We will try to delegate as much computation as possible to the client.

|===
| **Advantages** | **Disadvantages**
| Less dependence on the server. | Less secure.
| The server requires fewer resources. |
|===

As this is an open source project whose code is already available on github and we don't expect to have any heavy computations, we decided that the best option was to try decoupling the application as much as possible from the server.


