[[section-technical-risks]]
== Risks and Technical Debts

=== Risks
[options="header",cols="1,2,2"]
|===
|Risk|Description|Approach
| _Steep technology learning curve_
| _We have not used Typescript, React nor SOLID before, so we could get stuck or slowed down while we learn how to use
them. We might encounter additional topics to explore later in the development (for example, using Resource Development
Format for representing information in the pods)._
| _Follow the introduction and bibliography provided by the teachers, look for solutions in community forums._
| _Time scarcity_
| _We can run out of time to develop all that is required in each deliverable, and provide what is asked at each
deadline._
| _Impose intermediate checkpoints, establish a constant and maintainable development speed. Develop functional things
first and build (improve) from that point on._
| _Coordination problems_
| _Some people can destroy the work of others due to version control management errors, and there can be
misunderstandings about the work to do and how._
| _Follow the indications of the teachers regarding the use of Github (issues, pull requests) and work in a disciplined
way. Use WhatsApp and Teams to stay in contact._
| _First experience in a project with full responsibility on every step._
| _This is the first time we are involved in developing a project from scratch, from deciding architecture and design
to develop a full-fledged application, and we have to reach agreements on many decisions, which can be wrong and cost
us a lot of time and effort._
| _Apply what we know, combine with the suggestions of every member of the team and complement those ideas with what we
learn in this semester (not only in this subject, but other ones). Follow the guidelines for each part of the project._
| _Security weak spots_
| _The accessibility of data, and who can get it, can vary depending on the situation, and therefore there are many
fronts on which information can be reached when it should not, and viceversa._
| _Explore the different mechanisms that SOLID provides to control and change the access to data, and study carefully
every case._
| _Scalability issues_
| _Due to the nature of the application, we need to have an acceptable performance with not only many users, but users
with lots of data and/or that perform many accesses._
| _This will be studied at due time, once we start to implement the application, to approach certain aspects or refactor
them in a way that the application can handle a greater workload._
|===

=== Technical debts
[options="header",cols="1,2,2"]
|===
|Risk|Description|Approach
| _Code quality_
| _In order to deliver software that can fulfill the requirements punctually, and given our lack of experience, some
aspects (like readability, homogeneity, extensibility) were sacrificed so that the delivered prototype has the required
functionality. This could hinder the evolution of the application, as we head towards a complete product and many features
will be added, continuing from the code that we have done so far._
| _Identify the code that is subject to change or will be used by other developers, and refactor it so that it is
readable, maintainable and scalable. Prioritize what must be refactored regarding the available time to fulfill the next
objectives._
| _Server code development_
| _Given our architectural and design decisions, where the server handles the database with the public places, we have
not focused in this part as the functionality that has been required thus far did not involve that. So, we have to face
the implementation of the server from a very early phase, compared to a team that has taken a different approach. In
conclusion, we may face more trouble than expected when working on the restapi, the database and the deployment._
| _Divide the tasks in such a way that the database and the restapi could be developed in parallel, so that the
functionality of the centralized database can be inserted as smoothly as possible. Ideally, having the means to connect
the webapp with the server with generous time margin, so that we can react to problems that could arise in the first
attempts._

|===

[role="arc42help"]
****
.Contents
A list of identified technical risks or technical debts, ordered by priority

.Motivation
“Risk management is project management for grown-ups” (Tim Lister, Atlantic Systems Guild.) 

This should be your motto for systematic detection and evaluation of risks and technical debts in the architecture, which will be needed by management stakeholders (e.g. project managers, product owners) as part of the overall risk analysis and measurement planning.

.Form
List of risks and/or technical debts, probably including suggested measures to minimize, mitigate or avoid risks or reduce technical debts.
****
